version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Download mock-app from Bucket to build it
          command: wget -O app.zip $DOWNLOAD_APP_URI
      - run:
          name: Unzip archive
          command: unzip app.zip && cd $GITHUB_ARCHIVE_ROOT_DIR
      - run:
          name: Install Heroku client
          command: wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Create Heroku app
          command: heroku create --region=eu --json $MOCK_APP_DOMAIN >> heroku_create.json
      - run:
          name: Login to registry
          command: heroku container:login
      - run:
          name: Deploy to Heroku
          command: |
            cd $GITHUB_ARCHIVE_ROOT_DIR
            heroku container:push web --app $MOCK_APP_DOMAIN
            heroku container:release web --app $MOCK_APP_DOMAIN
      - run:
          name: App info
          command: |
            sudo apt-get install jq libssl
            cat heroku_create.json | jq .
      - run:
          name: Touch app
          command: |
            python -c "import urllib2; print(urllib2.urlopen('https://google.com', timeout=30).read())" | jq .

