version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Download mock-app from Bucket to build it
          command: wget $DOWNLOAD_APP_URI
      - run:
          name: Unzip archive
          command: unzip ${MOCK_APP_NAME}.zip $MOCK_APP_NAME ./
      - run:
          name: Build docker image
          command: docker build -t protocall/$MOCK_APP_NAME:latest .
      - run:
          name: Install Heroku client
          command: wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Install Heroku plugins
          command: heroku plugins:install heroku-container-registry
      - run:
          name: Create Heroku app
          command: heroku create $MOCK_APP_DOMAIN
      - run:
          name: Login to registry
          command: docker login -e _ -u _ --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Push image to Heroku
          command: heroku container:push web --app $MOCK_APP_DOMAIN
