version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Download mock-app from Bucket to build it
          command: wget -O app.zip $DOWNLOAD_APP_URI
      - run:
          name: Build docker image
          command: |
            unzip app.zip && cd $GITHUB_ARCHIVE_ROOT_DIR
            docker build -t protocall/$MOCK_APP_NAME:latest .
      - run:
          name: Install Heroku client
          command: wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Create Heroku app
          command: heroku create --region=eu --json $MOCK_APP_DOMAIN >> heroku_create.json
      - run:
          name: Login to registry
          command: heroku container:login
      - run:
          name: Push image to Heroku
          command: |
            cd $GITHUB_ARCHIVE_ROOT_DIR
            heroku container:push web
